services:
  saldofacile:
    container_name: saldofacile
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "8500:8500"
    restart : always